inherit_from:
  - https://raw.githubusercontent.com/rails/rails/5-2-stable/.rubocop.yml

AllCops:
  Exclude:
    - gakubuchi.gemspec
    - spec/dummy/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb

LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal
